name: image_editor_pro
description: Image Editor Plugin with simple, easy support for image editing using paints,text and emoji like stories.
version: 1.0.9
homepage: https://github.com/zeeshux7860/Image_editor_pro_package

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  zoom_widget: ^0.1.3
  font_awesome_flutter: ^8.11.0
  image_picker: ^0.6.7+21
  path_provider: ^2.0.1
  image_gallery_saver: ^1.6.7
  permission_handler: ^5.0.1+1
  dio: ^3.0.10
  screenshot: ^0.2.0
  signature: ^3.2.0
  flutter_colorpicker: ^0.3.5

dev_dependencies:
  pedantic: ^1.9.2

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: zeeshux7860.update.image_editor_pro
        pluginClass: ImageEditorProPlugin
      ios:
        pluginClass: ImageEditorProPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
